services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: front-end
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: back-end
    environment:
      ENV NODE_ENV: "production"
    ports:
      - 3000:3000
    restart: always

